version: '3.1'

services:
  db:
    container_name: mysql8-oauth2-casadocodigo
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' 
    ports:
      - 3306:3306
    volumes:
      - type: bind
        source: /home/akio/Db/mysql/
        target: /var/lib/mysql

networks:
  bridge-casa-do-codigo:
    driver: bridge